#!/bin/sh

ssh -t -t ec2-user@ip-172-31-91-180 <<EOF 

  cd ~/<YOUR_REPO_FOLDER>

  git pull origin main

  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash

  . ~/.nvm/nvm.sh

  nvm install --lts

  npm install

  npm install -g pm2

  pm2 kill

  pm2 start server.js -f

  exit

EOF